# format = """\
# [â”Œâ”€â”€](#7DF9AA)\
# [î‚¶](bg:#030B16 fg:#7DF9AA)\
# [î¯‰ ](bg:#7DF9AA fg:#090c0c)\
# [î‚°](fg:#7DF9AA bg:#1C3A5E)\
# $time\
# [î‚°](fg:#1C3A5E bg:#3B76F0)\
# $directory\
# [î‚°](fg:#3B76F0 bg:#FCF392)\
# $git_branch\
# [î‚°](fg:#FCF392 bg:#f542f2)\
# $python\
# $nodejs\
# [î‚°](fg:#f542f2 bg:#030B16)\
# $battery
# [â”‚](#7DF9AA)
# [â””â”€â”€â”€î˜‚](#7DF9AA)
# """

[hostname]
ssh_only = false
format = "[gss-ubuntu](bold yellow) "
disabled = false

[username]
style_user = " green bold"
style_root = "red bold"
disabled = true
show_always = true

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
format = "[$path ]($style)"
truncation_symbol = "../"
read_only = " ï€£"
truncation_length = 2
style = "bold italic #8cdff1"
truncate_to_repo = true

[python]
symbol = "î˜† "
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[nodejs]
format = "via [ó°™ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[java]
symbol = "î‰– "
style = "red"

[package]
symbol = "ï£– "

[git_branch]
format = 'on[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "îœ‰ ï˜ "
style = "bold #ec73b3"

[git_status]
format = '[\[$all_status\]]($style) '
style = "bold #ec73b3"

# [git_metrics]
# format = "([+$added]($added_style))[]($added_style)"
# added_style = "fg:#1C3A5E"
# deleted_style = "fg:bright-red bg:235"
# disabled = false

[cmd_duration]
min_time = 5
disabled = false

# [time]
# disabled = false
# time_format = "%I:%M %p" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[ ó±‘ $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "ğŸ”Œ"
# discharging_symbol = "âš¡ï¸"
# format = "[ <$symbol$percentage > ]($style)"

# [[battery.display]]
# threshold = 30
# style = "bold red"
